name: Hack
on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: token
        with:
          server: 'https://f0e3-99-250-87-101.ngrok.io'
          repositories: |
            - thepwagner/github-token-action
            - thepwagner/github-token-action-server
          permissions: |
            contents: read
      - run: |
          mkdir 'tmp'
          cd tmp
          git clone "https://x-access-token:${{steps.token.outputs.token}}@github.com/thepwagner/github-token-action.git"
          git clone "https://x-access-token:${{steps.token.outputs.token}}@github.com/thepwagner/github-token-action-server.git"
          ls -l
          echo 'two private repos, cool trick eh?'
